DROP TABLE IF EXISTS WEAPON_TYPE;

CREATE TABLE WEAPON_TYPE (
  id BIGINT IDENTITY NOT NULL PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS WEAPON;

CREATE TABLE WEAPON (
	id BIGINT IDENTITY NOT NULL PRIMARY KEY,
	name VARCHAR(250) NOT NULL,
	weapontype_id BIGINT DEFAULT NULL
);

ALTER TABLE WEAPON ADD FOREIGN KEY (weapontype_id) REFERENCES WEAPON_TYPE(id);