DROP TABLE IF EXISTS WEAPON_TYPE;

CREATE TABLE WEAPON_TYPE (
  id BIGINT IDENTITY NOT NULL PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS WEAPON;

CREATE TABLE WEAPON (
	id BIGINT IDENTITY NOT NULL PRIMARY KEY,
	name VARCHAR(250) NOT NULL,
	weapontype_id BIGINT DEFAULT NULL,
	dexreq INT DEFAULT 0,
	strengreq INT DEFAULT 0,
	intreq INT DEFAULT 0
);

ALTER TABLE WEAPON ADD FOREIGN KEY (weapontype_id) REFERENCES WEAPON_TYPE(id);

DROP TABLE IF EXISTS BUILD;

CREATE TABLE BUILD(
	id BIGINT IDENTITY NOT NULL PRIMARY KEY,
	name VARCHAR(250),
	level INT,
	dexterity INT,
	strength INT,
	intelect INT,
	weapon1_id BIGINT DEFAULT NULL,
	weapon2_id BIGINT DEFAULT NULL
);

ALTER TABLE BUILD ADD FOREIGN KEY (weapon1_id) REFERENCES WEAPON(id);
ALTER TABLE BUILD ADD FOREIGN KEY (weapon2_id) REFERENCES WEAPON(id);